### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by qt20191125** [ddpom/toolsRes#10]
几乎清空了所有内容  command+s或者pdflatex或者xelatex或者bibtex或者latexmk都不报错，但是pdflatex-bibtex-pdflatex*2会报错。错误信息为Label(s) may have changed. Rerun to get cross-references right.
File `dpp.out' has changed.
(rerunfilecheck)	Rerun to get outlines right
(rerunfilecheck)	or use package `bookmark'.
请问该怎么办呢？

**Comment by sierxue** [comment]
1. 设置好编译方式。在 vs code 里面，用缺省的设置就是最好的设置。
2. 分清楚错误信息的类别。错误通常有两种：error 和 warnings. 有些 Warnings 不影响正常编译，可以忽略。
3. 和 label 相关的报错，可以考虑先清空编译过程中的中间文件。
