### ISSUE TITLE
 \mathbb{}报错

### ISSUE THREAD

**Issue by qt20191125** [ddpom/toolsRes#11]
1、\mathbb{}报错如下：
Undefined control sequence.
<recently read> \mathbb 

是不是要引入宏包\usepackage{amssymb}来解决。
论文中我已用其他可用符号代替了。
2、定义符号，即等号上面一个三角形，也报错。我换成了恒等号：≡，没有报错。

**Comment by sierxue** [comment]
是的，需要宏包 amssymb. 我已经加载了。定义符号，你使用的 latex 命令是什么？

**Comment by qt20191125** [comment]
\triangleq  谢谢问题已经解决
