### ISSUE TITLE
参考文献是问号

### ISSUE THREAD

**Issue by qt20191125** [ddpom/toolsRes#12]
\cite{elmachtoub_value_2021}
\cite{ban_personalized_2021}
xe-bib-xe-xe编译后，参考文献引用是问号。错误提示为：
Undefined control sequence.
<argument> Ban \protect \BIBand 
Undefined control sequence.
<argument> ...Elmachtoub, Gupta, \protect \BIBand 

但使用thebibliography环境时，xe-bib-xe-xe编译没错，引用也没有问题。
例如
\cite{liuhaiyang2013latex}.
\cite{ban_personalized_2021}.
\begin{thebibliography}{2}
    \bibitem[1]{liuhaiyang2013latex}
    刘海洋.
    abc入门 J.
    电子工业出版社. 
    \bibitem[Ban Keskin(2021)] {ban_personalized_2021}
    Ban GY, Keskin NB(2021) Personalized Dynamic Pricing with Machine Learning: High Dimensional Features and Heterogeneous Elasticity.
    Fprthcoming, Management Science.
\end{thebibliography}

**Comment by sierxue** [comment]
加入了 natbib 的设置后，就没有问题了。
