### ISSUE TITLE
\subfloat排列子图时错误

### ISSUE THREAD

**Issue by qt20191125** [ddpom/toolsRes#13]
为了使用\subfloat可用排列多个子图  我引入\usepackage{subfig}不知道这是不是最好的解决办法

**Comment by sierxue** [comment]
subfloat 和 subfigure 这两个都有不兼容其它 package 的问题。参考 [subfigure and subfig packages deprecated](https://tex.stackexchange.com/questions/144782/subfigure-and-subfig-packages-deprecated). 

我们以后可以使用 subcaption, 其语法和 subfloat 类似。
