### ISSUE TITLE
Latex 导入图片的时候，图片说明为什么会显示 ”图 1 “呢？

### ISSUE THREAD

**Issue by Tonywangrui** [ddpom/toolsRes#2]
我也是用的\caption{Figure 1}
但编译出来会有一个图1在标题前面
这是我latex的初始设置
![1576753262](https://user-images.githubusercontent.com/42131512/71168565-0274cc80-2292-11ea-8c04-0cdb0f877eb2.png)

**Comment by ddpom** [comment]
对于 [ElegantPaper](https://github.com/ElegantLaTeX/ElegantPaper) 模板，如果想写全英文论文，要在 documentclass 的选项中设定 lang=en.
